/**
 * Table of Contents generation for the vault
 * Creates and updates _TOC.md with vault structure
 */

import { readFile, writeFile, readdir, stat } from "fs/promises";
import { join, basename, dirname, relative } from "path";
import matter from "gray-matter";
import { glob } from "glob";
import {
  getVaultPath,
  getTimezone,
  readVaultFile,
  findMarkdownFiles,
  parseTasksMain,
} from "./vault.js";

interface TocSection {
  title: string;
  items: TocItem[];
  subsections?: { title: string; items: TocItem[] }[];
}

interface TocItem {
  name: string;
  path: string;
  tags?: string[];
  dueDate?: string;
  completed?: boolean;
}

/**
 * Generate the full TOC markdown content
 */
async function generateTocContent(): Promise<string> {
  const vaultPath = getVaultPath();
  const sections: TocSection[] = [];

  // Tasks section
  const tasksSection = await generateTasksSection();
  sections.push(tasksSection);

  // Memory section
  const memorySection = await generateMemorySection();
  sections.push(memorySection);

  // Research section
  const researchSection = await generateResearchSection();
  sections.push(researchSection);

  // Writing section
  const writingSection = await generateWritingSection();
  sections.push(writingSection);

  // Build markdown
  const now = new Date().toISOString();
  let md = `---
generated: ${now}
---

# Vault Table of Contents

`;

  for (const section of sections) {
    md += `## ${section.title}\n\n`;

    if (section.subsections) {
      for (const sub of section.subsections) {
        md += `### ${sub.title}\n`;
        if (sub.items.length === 0) {
          md += `(empty)\n\n`;
        } else {
          for (const item of sub.items) {
            const status = item.completed ? " (completed)" : "";
            md += `- [[${item.name}]]${status}\n`;
          }
          md += "\n";
        }
      }
    } else {
      if (section.items.length === 0) {
        md += `(empty)\n\n`;
      } else {
        for (const item of section.items) {
          md += `- [[${item.name}]]\n`;
        }
        md += "\n";
      }
    }
  }

  const tz = getTimezone();
  md += `---\n\n*Generated by MCP server. Last updated: ${new Date().toLocaleString("en-US", { timeZone: tz })} (${tz})*\n`;

  return md;
}

/**
 * Generate Tasks section from Tasks/Main.md
 */
async function generateTasksSection(): Promise<TocSection> {
  const { dueToday, dueThisWeek, ongoing } = await parseTasksMain();

  // Find project folders
  const vaultPath = getVaultPath();
  const tasksPath = join(vaultPath, "Tasks");
  const entries = await readdir(tasksPath, { withFileTypes: true });
  const projectFolders = entries
    .filter(
      (e) => e.isDirectory() && !e.name.startsWith("_") && e.name !== "Hiring"
    )
    .map((e) => e.name);

  // Check for Hiring folder
  const hasHiring = entries.some(
    (e) => e.isDirectory() && e.name === "Hiring"
  );

  return {
    title: "Tasks",
    subsections: [
      {
        title: `Due Today (${dueToday.length})`,
        items: dueToday.map((t) => ({
          name: t.name,
          path: `Tasks/${t.name}.md`,
          completed: t.completed,
        })),
      },
      {
        title: `Due This Week (${dueThisWeek.length})`,
        items: dueThisWeek.map((t) => ({
          name: t.name,
          path: `Tasks/${t.name}.md`,
          completed: t.completed,
        })),
      },
      {
        title: `Ongoing (${ongoing.length})`,
        items: ongoing.map((t) => ({
          name: t.name,
          path: `Tasks/${t.name}.md`,
          completed: t.completed,
        })),
      },
      {
        title: "Projects",
        items: [
          ...projectFolders.map((p) => ({
            name: `${p}/`,
            path: `Tasks/${p}/`,
          })),
          ...(hasHiring
            ? [{ name: "Hiring/", path: "Tasks/Hiring/" }]
            : []),
        ],
      },
    ],
    items: [],
  };
}

/**
 * Generate Memory section with subdirectories
 */
async function generateMemorySection(): Promise<TocSection> {
  const vaultPath = getVaultPath();
  const memoryPath = join(vaultPath, "Memory");

  // Get subdirectories
  const entries = await readdir(memoryPath, { withFileTypes: true });
  const subdirs = entries
    .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
    .map((e) => e.name);

  // Get root-level files
  const rootFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith(".md"))
    .map((e) => basename(e.name, ".md"));

  const subsections: { title: string; items: TocItem[] }[] = [];

  // Process each subdirectory
  for (const subdir of subdirs) {
    const files = await findMarkdownFiles(`Memory/${subdir}`, {
      recursive: false,
    });
    subsections.push({
      title: subdir,
      items: files.map((f) => ({
        name: basename(f, ".md"),
        path: f,
      })),
    });
  }

  // Add root-level files as "Other" section if any
  if (rootFiles.length > 0) {
    subsections.push({
      title: "Other",
      items: rootFiles.map((name) => ({
        name,
        path: `Memory/${name}.md`,
      })),
    });
  }

  return {
    title: "Memory",
    subsections,
    items: [],
  };
}

/**
 * Generate Research section
 */
async function generateResearchSection(): Promise<TocSection> {
  const vaultPath = getVaultPath();
  const researchPath = join(vaultPath, "Research");

  const entries = await readdir(researchPath, { withFileTypes: true });

  // Get root files
  const rootFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith(".md"))
    .map((e) => basename(e.name, ".md"));

  // Get subdirectories
  const subdirs = entries
    .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
    .map((e) => e.name);

  const subsections: { title: string; items: TocItem[] }[] = [];

  if (rootFiles.length > 0) {
    subsections.push({
      title: "Root",
      items: rootFiles.map((name) => ({
        name,
        path: `Research/${name}.md`,
      })),
    });
  }

  for (const subdir of subdirs) {
    const files = await findMarkdownFiles(`Research/${subdir}`, {
      recursive: false,
    });
    subsections.push({
      title: subdir,
      items: files.map((f) => ({
        name: basename(f, ".md"),
        path: f,
      })),
    });
  }

  return {
    title: "Research",
    subsections: subsections.length > 0 ? subsections : undefined,
    items:
      subsections.length === 0
        ? rootFiles.map((name) => ({
            name,
            path: `Research/${name}.md`,
          }))
        : [],
  };
}

/**
 * Generate Writing section
 */
async function generateWritingSection(): Promise<TocSection> {
  const vaultPath = getVaultPath();
  const writingPath = join(vaultPath, "Writing");

  let entries: Awaited<ReturnType<typeof readdir>>;
  try {
    entries = await readdir(writingPath, { withFileTypes: true });
  } catch {
    return {
      title: "Writing",
      items: [],
    };
  }

  // Get root files (active drafts)
  const rootFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith(".md"))
    .map((e) => basename(e.name, ".md"));

  // Get subdirectories (platforms, projects)
  const subdirs = entries
    .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
    .map((e) => e.name);

  const subsections: { title: string; items: TocItem[] }[] = [];

  if (rootFiles.length > 0) {
    subsections.push({
      title: "Active Drafts",
      items: rootFiles.map((name) => ({
        name,
        path: `Writing/${name}.md`,
      })),
    });
  }

  for (const subdir of subdirs) {
    const files = await findMarkdownFiles(`Writing/${subdir}`, {
      recursive: true,
    });
    if (files.length > 0) {
      subsections.push({
        title: subdir,
        items: files.map((f) => ({
          name: basename(f, ".md"),
          path: f,
        })),
      });
    }
  }

  return {
    title: "Writing",
    subsections: subsections.length > 0 ? subsections : undefined,
    items:
      subsections.length === 0
        ? [{ name: "(no active drafts)", path: "" }]
        : [],
  };
}

/**
 * Regenerate the TOC file
 */
export async function regenerateToc(): Promise<void> {
  const vaultPath = getVaultPath();
  const tocPath = join(vaultPath, "_TOC.md");
  const content = await generateTocContent();
  await writeFile(tocPath, content, "utf-8");
}

/**
 * Read the current TOC
 */
export async function readToc(): Promise<string> {
  const vaultPath = getVaultPath();
  const tocPath = join(vaultPath, "_TOC.md");
  try {
    return await readFile(tocPath, "utf-8");
  } catch {
    // If TOC doesn't exist, generate it
    await regenerateToc();
    return await readFile(tocPath, "utf-8");
  }
}

// Allow running directly to generate TOC
if (import.meta.main) {
  regenerateToc()
    .then(() => console.log("TOC generated successfully"))
    .catch((err) => console.error("Failed to generate TOC:", err));
}
